/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index/movie-details` | `/index/movie-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search/movie-details` | `/search/movie-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/watchlist/movie-details` | `/watchlist/movie-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/watchlist/watchlist` | `/watchlist/watchlist`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/index/movie-details` | `/index/movie-details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search/movie-details` | `/search/movie-details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/watchlist/movie-details` | `/watchlist/movie-details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/watchlist/watchlist` | `/watchlist/watchlist`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/index${`?${string}` | `#${string}` | ''}` | `/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/index/movie-details${`?${string}` | `#${string}` | ''}` | `/index/movie-details${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search/movie-details${`?${string}` | `#${string}` | ''}` | `/search/movie-details${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/watchlist/movie-details${`?${string}` | `#${string}` | ''}` | `/watchlist/movie-details${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/watchlist/watchlist${`?${string}` | `#${string}` | ''}` | `/watchlist/watchlist${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index/movie-details` | `/index/movie-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search/movie-details` | `/search/movie-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/watchlist/movie-details` | `/watchlist/movie-details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/watchlist/watchlist` | `/watchlist/watchlist`; params?: Router.UnknownInputParams; };
    }
  }
}
